[package]
name = "rsmtp"
version = "0.1.3"
description = "Utility functions for SMTP applications, no backwards compatibility guarantees."
authors = ["Conrad Kleinespel <conradk@conradk.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
libc = "0.2"
