name: rclio rust tests

on:
  pull_request:
    paths:
      - "projects/rclio/**.toml"
      - "projects/rclio/**.rs"
      - "projects/rprompt/**.toml"
      - "projects/rprompt/**.rs"
      - "projects/rpassword/**.toml"
      - "projects/rpassword/**.rs"
      - "projects/rutil/**.toml"
      - "projects/rutil/**.rs"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Install rust
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Run cargo test
        with:
          command: test
          args: --all-targets --all-features --manifest-path projects/rclio/Cargo.toml

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Install rust
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Run cargo test
        with:
          command: test
          args: --all-targets --all-features --manifest-path projects/rclio/Cargo.toml
