name: rooster rust tests

on:
  pull_request:
    paths:
      - "projects/rooster/**.toml"
      - "projects/rooster/**.rs"
      - "projects/rclio/**.toml"
      - "projects/rclio/**.rs"
      - "projects/rpassword/**.toml"
      - "projects/rpassword/**.rs"
      - "projects/rprompt/**.toml"
      - "projects/rprompt/**.rs"
      - "projects/rtoolbox/**.toml"
      - "projects/rtoolbox/**.rs"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt install curl unzip pkg-config libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libx11-dev libxmu-dev python3 libssl-dev libsodium-dev xsel
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Install rust
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Run cargo test
        with:
          command: test
          args: --all-targets --all-features --manifest-path projects/rooster/Cargo.toml
