name: rooster docker tests

on:
  pull_request:
    branches:
      - master
    paths:
      - "projects/rooster/**"
      - "projects/rpassword/**"

jobs:
  docker-build-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./projects/
          file: ./projects/rooster/Dockerfile.alpine
          platforms: linux/amd64
          push: false
          tags: rooster:latest
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./projects/
          file: ./projects/rooster/Dockerfile.debian
          platforms: linux/amd64
          push: false
          tags: rooster:latest
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./projects/
          file: ./projects/rooster/Dockerfile.fedora
          platforms: linux/amd64
          push: false
          tags: rooster:latest
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./projects/
          file: ./projects/rooster/Dockerfile.ubuntu1604
          platforms: linux/amd64
          push: false
          tags: rooster:latest
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./projects/
          file: ./projects/rooster/Dockerfile.ubuntu1804
          platforms: linux/amd64
          push: false
          tags: rooster:latest
